imx95: Add NavQ95 support
imxrt: updated include path to queue.h

imxrt: adapt board_crashdump.c to new NuttX interface

imxrt: fix method to get free stack space

imxrt: fix name collision on stack_t

imxrt: adapt semaphores to new interface

imxrt: update type of _vectors

imxrt: add link dependency for nuttx_drivers

imxrt: Mount romfs

imxrt: Use inc_dir prefix instead of incdir tool

imx95: add first draft of imx95 based on imxrt (wip)

imx95: nsh is working

imx95: create jlink-nuttx.so only when CONFIG_DEBUG_FEATURES

imx95: High resolution timer uses tstmr & lpit1/2 (default to lpit2)

navq95: hrt update

imx95 hrt use LPTMR peripheral

imx95-navq: run from ddr

imx95: basic enablement for SPI

pinirq still wip

imx9: lptmr hrt fix

imx95-navq: format

imx95-navq: add tpm

imx9: hrt use lpit for isr deadlines

imx95 enable lpspi and romfs

imx95-navq: enable rpmsg tty

imx95-navq: enable rpmsg fs

imx95-navq: enable ttyS6 and use it for RC

imx95-navq: configure RC(SBUS) in px4

imx95-navq: set ROMFS dir to px4fmu_common

imx95-evk: Enable CANFD5

imx95-evk: MC/FW config enable fix startup and disable conflicting RC

UAVCAN SocketCAN dont' error on missing CAN_RAW_TX_DEADLINE

Give a warning instead that CAN_RAW_TX_DEADLINE is disabled.

imx95-evk: Enable UAVCAN

Note CAN_RAW_TX_DEADLINE is disabled needs more debugging

imx95 default target flash

Seperate nxp_imx95_ddr target
Add ITCM support and move interrupt to itcm
Update defconfig

imx95 enable MPU

imx95-navq: rebase NuttX

CAN and UAVCAN are disabled because of build errors
No functions are placed in ITCM to solve runtime errors

imx95-navq: reenable CAN and UAVCAN

mavlink: add UART raw mode

imx95: start mavlink in raw and wait mode

mr-canhubk3: fix build

ucan32k146: fix build

imx95: fix imu orientation

imx95: PWM allow 20kHz frequency

Needed to control B3RB

imx95: Update config for CAN / MPU and RPMSG caching

Enabling MPU causes instability instead we let OPENAMP RPMSG flush the
correct cache lines

Enable I2C8 and INA226 driver

ucan: update ucan defconfig to new nuttx

imx95-navq: add rpmsg /dev/ttyros for ros bridge

imx95: run mavlink in offboard mode

Gives more data sensors higher update rate

imx95 enable uxrce

imx95-navq: add nsh console on rpmsg uart /dev/ttynsh

imx95 use ITCM

imx95: add -fno-builtin flag to init.c to fix ITCM copy

imx95: updated nuttx and renamed instruction ram init function

imx95: update io_pins to new imx9_tpm header format

update to newer nuttx

imx95 enable dma for lpspi1

update nuttx

Fix EDMA5 sharing with Cortex-A

BMI088 GPIO2 CS hack for sharing with Linux

nuttx sync fix

fixing:
common/crt0.c:27:10: fatal error: nuttx/config.h: No such file or directory
   27 | #include <nuttx/config.h>

nuttx sync fix

fixes:
src/drivers/uavcan/uavcan_drivers/socketcan/driver/src/thread.cpp:82:18: error: 'sem_t' {aka 'struct sem_s'} has
no member named 'semcount'
   82 |         if (sem_.semcount <= 0) {

nuttx sync fix

fixes for nuttx commit b8e30b54ec9c3092cb44394cdb6a4958dd6d3b42

Add mcuboot header to binary

build navq95 with:

make nxp_imx95_default
scripts/imgtool.py sign --version 1.0.0 --header-size 0x800\
 --slot-size 0x700000 --pad-header build/nxp_imx95_default/nxp_imx95_default.bin\
 build/nxp_imx95_default/nxp_imx95_default.signed.bin

nuttx sync

fixes for nuttx commit: 5d7ac216f2c08f0b0593b744ba479f2ffc772231

nuttx sync

fixes for nuttx commit ca7608c2ac3aeedefcf02817b5e466d3c53aba2c

Force ours merge strategy for NuttX directories and .gitmodules

Revert conflicts

Update board support for mr_navq95b

Reduce OCRAM size to 256kB

Fix BMI088 and GPIO drdy irq

Fix PWM mapping and GPIO irq registering

imx95: Fix DMA and I2C1

Fix sensors and add dshot

Fix startup sequencing with gcc 13.2 optmizations